# Generated by Django 4.1.6 on 2023-03-22 23:31

from django.db import migrations
from utilities.inventory_data_migration import initialize_database as inventory_init

class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        ('items', '0003_alter_item_purchase_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(inventory_init),
    ]
