# Generated by Django 4.1.6 on 2023-03-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, help_text='Enter price of item in American cents (ex. $23.56 => 2356).', null=True),
        ),
    ]
