# Generated by Django 4.1.6 on 2023-02-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_image_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_file']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
