# Generated by Django 4.1.6 on 2023-03-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Enter date the item was purchased.', null=True),
        ),
    ]
