# Generated by Django 4.1.6 on 2023-02-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_image_options_remove_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of brand (required).', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='borroweditem',
            options={'ordering': ['-date', 'item']},
        ),
        migrations.AlterModelOptions(
            name='gifteditem',
            options={'ordering': ['-date', 'item']},
        ),
        migrations.AlterModelOptions(
            name='solditem',
            options={'ordering': ['-date', 'item']},
        ),
        migrations.AlterModelOptions(
            name='thrownawayitem',
            options={'ordering': ['-date', 'item']},
        ),
        migrations.AddField(
            model_name='solditem',
            name='price_sold',
            field=models.IntegerField(blank=True, default=0, help_text='Enter price the item sold for in American cents (ex. $23.56 => 2356).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Enter brand of the item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.brand'),
        ),
    ]
