# Generated by Django 4.1.6 on 2023-02-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_brand_alter_borroweditem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='action_state_id',
            field=models.UUIDField(blank=True, help_text='Enter ID of ActionItem child model (ex. BorrowedItem id with matching Item id).', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('', 'In Possession'), ('BRWD', 'Borrowed'), ('GFTD', 'Gifted'), ('SLD', 'Sold'), ('THRWN', 'Thrown Away')], default='', max_length=5),
        ),
    ]
