# Generated by Django 4.1.6 on 2023-03-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_action_state_id_item_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('POS', 'In Possession'), ('BRWD', 'Borrowed'), ('GFTD', 'Gifted'), ('SLD', 'Sold'), ('THRWN', 'Thrown Away')], default='POS', max_length=5),
        ),
    ]
