# Generated by Django 4.1.6 on 2023-02-20 23:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Enter person's full name (required).", max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text="Enter person's full name.", max_length=10)),
                ('email', models.EmailField(blank=True, help_text="Enter person's email.", max_length=254)),
                ('thumbnail', models.ImageField(blank=True, help_text="Enter person's thumbnail image.", upload_to='')),
            ],
        ),
    ]
