# Generated by Django 4.1.6 on 2023-02-20 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(help_text='Enter user that owns the inventory (required).', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Enter name of the inventory group.', max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(help_text='Enter inventory that the inventory group belongs to (required).', on_delete=django.db.models.deletion.CASCADE, to='inventories.inventory')),
                ('items', models.ManyToManyField(blank=True, help_text='Enter items that belong in the inventory group.', to='items.item')),
            ],
            options={
                'ordering': ['name', '-last_modified'],
            },
        ),
    ]
