# Generated by Django 4.1.6 on 2023-03-19 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='InventoryGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Enter name of the inventory group.', max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(help_text='Enter inventory that the inventory group belongs to (required).', on_delete=django.db.models.deletion.CASCADE, to='inventories.inventory')),
            ],
            options={
                'ordering': ['name', '-last_modified'],
            },
        ),
    ]
